In [1]:
# impotando tudo da biblioteca, usando "as" para apelidar a biblioteca
import pandas as pd

# importando um recurso especifico da biblioteca 
from pandas import Series, DataFrame

# importando outra biblioteca
import numpy as np

### Criar dados para teste de seleção

In [3]:
dados = np.arange(10)
dados

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# posicionando os dados em colunas e linhas
dados = np.arange(10)
dados.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### indexando nome aos dados e facilitando a busca

In [5]:
indices = ['l1','l2','l3','l4','l5','l6','l7','l8','l9','l10']

In [6]:
dados

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
serie = pd.Series(dados, index=indices)

In [8]:
serie

l1     0
l2     1
l3     2
l4     3
l5     4
l6     5
l7     6
l8     7
l9     8
l10    9
dtype: int32

In [9]:
serie['l8']

7

In [11]:
# criando com numeros aleatorios um conjunto a ser definido como semente 
np.random.seed(None)
numAleatorios = np.random.rand(25).reshape(5,5)
numAleatorios

array([[0.31990216, 0.47073395, 0.17464854, 0.52937127, 0.82791737],
       [0.92550993, 0.04332637, 0.58998028, 0.5033752 , 0.59437685],
       [0.38067057, 0.23459856, 0.69869547, 0.31993697, 0.62337356],
       [0.83102965, 0.88661269, 0.93698346, 0.55752968, 0.65811553],
       [0.59418535, 0.20561046, 0.78018995, 0.10560784, 0.93597368]])

In [12]:
# indexando nomes as colunas e a linhas facilinatndo a localização do futuro DataFrame
linhas = ['l1','l2','l3','l4','l5']
colunas = ['c1','c2','c3','c4','c5']

In [14]:
# estabelecendo uma tabela com linhas e colunas usando DataFrame
tabela = pd.DataFrame(numAleatorios, index=linhas, columns=colunas)

In [15]:
tabela

c1        c2        c3        c4        c5
l1  0.319902  0.470734  0.174649  0.529371  0.827917
l2  0.925510  0.043326  0.589980  0.503375  0.594377
l3  0.380671  0.234599  0.698695  0.319937  0.623374
l4  0.831030  0.886613  0.936983  0.557530  0.658116
l5  0.594185  0.205610  0.780190  0.105608  0.935974

In [19]:
# extraindo dados especificos de uma tabela
tabela2 = tabela.loc[['l3','l4'],['c2','c3']]
tabela2

c2        c3
l3  0.234599  0.698695
l4  0.886613  0.936983

### Exercicios

In [24]:
# criando o conjunto e exibindo em serie 
temperaturas = [37.5, 38.0, 37.8, 38.5, 37.0, 38.2, 38.8, 37.6, 37.0]
serie = pd.Series(temperaturas)

In [25]:
media = serie.mean()
mediana = serie.median()
variancia = serie.var()
desvio = serie.std()

In [26]:
# especificando quantidade de casas decimais e definindo que será de forma arredondada, podendo também utilizar outros metodos para definir
print('Media', round(media,1))

Media 37.8


In [27]:
notas = [8.0, 9.0, 9.5, 6.0, 4.5, 4.0, 10.0, 10.0, 8.5, 8.0, 8.0, 8.0]
serie2 = pd.Series(notas)

In [33]:
media2 = serie2.mean()
print(round(media2,1))

7.8
