In [1]:
import numpy as np
import pandas as pd

In [12]:
dados = np.arange(10)
dados

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
indice = ['l1','l2','l3','l4','l5','l6','l7','l8','l9','l10']

In [14]:
serie = pd.Series(dados, index=indice)
serie

l1     0
l2     1
l3     2
l4     3
l5     4
l6     5
l7     6
l8     7
l9     8
l10    9
dtype: int32

In [15]:
serie = pd.Series(dados, index=indice)
serie['l2']

1

In [16]:
serie = pd.Series(dados, index=indice)
serie['l2':'l5']

l2    1
l3    2
l4    3
l5    4
dtype: int32

In [18]:
dados2 = dados.reshape(2,5)
dados2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
tabela = pd.DataFrame(dados2, index=['l1','l2'], columns=['c1', 'c2','c3','c4','c5'])
tabela

c1  c2  c3  c4  c5
l1   0   1   2   3   4
l2   5   6   7   8   9

In [24]:
np.random.seed(None)
aleatorios = np.random.rand(25).reshape(5,5)
aleatorios

array([[0.09713369, 0.62401079, 0.32934881, 0.44976123, 0.25073112],
       [0.62307502, 0.64904614, 0.10150555, 0.28399458, 0.1891775 ],
       [0.76513961, 0.90075021, 0.83857838, 0.11200953, 0.39679769],
       [0.17033998, 0.81294616, 0.99520039, 0.87241868, 0.88365108],
       [0.04277725, 0.07468825, 0.93360334, 0.79615665, 0.36439373]])

In [25]:
linhas = ['l1','l2','l3','l4','l5']
colunas = ['c1','c2','c3','c4','c5']

In [42]:
tabela = pd.DataFrame(aleatorios, index=linhas, columns=colunas)
tabela

c1        c2        c3        c4        c5
l1  0.097134  0.624011  0.329349  0.449761  0.250731
l2  0.623075  0.649046  0.101506  0.283995  0.189177
l3  0.765140  0.900750  0.838578  0.112010  0.396798
l4  0.170340  0.812946  0.995200  0.872419  0.883651
l5  0.042777  0.074688  0.933603  0.796157  0.364394

In [43]:
# Filtrando o DataFrame
filtro = tabela < 0.3
tabela2 = tabela[filtro]
tabela2

c1        c2        c3        c4        c5
l1  0.097134       NaN       NaN       NaN  0.250731
l2       NaN       NaN  0.101506  0.283995  0.189177
l3       NaN       NaN       NaN  0.112010       NaN
l4  0.170340       NaN       NaN       NaN       NaN
l5  0.042777  0.074688       NaN       NaN       NaN

In [46]:
# Modificando um valor nulo do DataFrame
filtro = tabela < 0.3
tabela2 = tabela[filtro]
tabela2['c1']['l2'] = -1
tabela2

c1        c2        c3        c4        c5
l1  0.097134       NaN       NaN       NaN  0.250731
l2 -1.000000       NaN  0.101506  0.283995  0.189177
l3       NaN       NaN       NaN  0.112010       NaN
l4  0.170340       NaN       NaN       NaN       NaN
l5  0.042777  0.074688       NaN       NaN       NaN

In [47]:
# Mostrando onde estão dados nulos
tabela2.isna()

c1     c2     c3     c4     c5
l1  False   True   True   True  False
l2  False   True  False  False  False
l3   True   True   True  False   True
l4  False   True   True   True   True
l5  False  False   True   True   True

In [48]:
# Contando quantos valores nulos em cada coluna
tabela2.isna().sum()

c1    1
c2    4
c3    4
c4    3
c5    3
dtype: int64

In [71]:
nan = np.nan
notas = [8,7,nan,9,7.5,10,7,nan,8]
notas = np.array(notas)
notas = notas.reshape(3,3)
notas

array([[ 8. ,  7. ,  nan],
       [ 9. ,  7.5, 10. ],
       [ 7. ,  nan,  8. ]])

In [72]:
tabelanota =pd.DataFrame(notas, index=['Thyago','Theo','sophia'], columns= ['python','java','banco de dados'])
tabelanota

python  java  banco de dados
Thyago     8.0   7.0             NaN
Theo       9.0   7.5            10.0
sophia     7.0   NaN             8.0

In [73]:
java = tabelanota['java']
java

Thyago    7.0
Theo      7.5
sophia    NaN
Name: java, dtype: float64

In [75]:
java = tabelanota['java']
java = java.fillna(java.mean())
tabelanota['java'] = java
tabelanota

python  java  banco de dados
Thyago     8.0  7.00             NaN
Theo       9.0  7.50            10.0
sophia     7.0  7.25             8.0

In [76]:
banco = tabelanota['banco de dados']
banco = banco.fillna(banco.mean())
tabelanota['banco de dados'] = banco
tabelanota

python  java  banco de dados
Thyago     8.0  7.00             9.0
Theo       9.0  7.50            10.0
sophia     7.0  7.25             8.0

In [79]:
python = tabelanota['python']
filtro = python > python.mean()
print(tabelanota[filtro])

      python  java  banco de dados
Theo     9.0   7.5            10.0
